apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: uhr9d2xrv-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: uhr9d2xrv-go 
  name: uhr9d2xrv-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: uhr9d2xrv-go 
